# Generated by Django 2.2 on 2019-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('running', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url')),
                ('instance_id_type', models.CharField(choices=[('date', 'date'), ('int', 'entier')], default=1, max_length=4, verbose_name='InstanceId type')),
                ('prefix', models.CharField(blank=True, max_length=500, null=True, verbose_name='prefix')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='start of date')),
                ('date_limit', models.DateField(blank=True, null=True, verbose_name='Limit of date')),
                ('id_limit', models.IntegerField(default=100, verbose_name='id max')),
                ('pages', models.ManyToManyField(blank=True, to='page.Page', verbose_name='Pages')),
            ],
            options={
                'verbose_name': 'Website',
            },
        ),
    ]
