# Generated by Django 2.2 on 2019-11-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='name')),
                ('url', models.CharField(blank=True, max_length=1000, verbose_name='url on Sharepoint')),
                ('local_url', models.CharField(blank=True, max_length=1000, verbose_name='url')),
                ('author', models.CharField(blank=True, max_length=1000, verbose_name='author')),
                ('datetime_creation', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Creation')),
                ('file_size', models.CharField(blank=True, max_length=10, verbose_name='Size')),
                ('file_version', models.CharField(blank=True, max_length=10, verbose_name='Version')),
                ('datetime_modified', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Modify')),
                ('modify_by', models.CharField(blank=True, max_length=1000, verbose_name='Modify by')),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Item',
            },
        ),
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='key')),
                ('value', models.CharField(max_length=500, verbose_name='value')),
            ],
            options={
                'verbose_name': 'Pair',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, verbose_name='slug')),
                ('datetime_begin', models.DateTimeField(blank=True, null=True, verbose_name='Datetime begin')),
                ('datetime_end', models.DateTimeField(blank=True, null=True, verbose_name='Datetime end')),
                ('body', models.TextField(verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url')),
                ('collections', models.ManyToManyField(blank=True, to='page.Collection', verbose_name='Collections')),
            ],
            options={
                'verbose_name': 'Page',
            },
        ),
    ]
