# Generated by Django 2.2 on 2019-11-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='ref_website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Website'),
        ),
        migrations.AddField(
            model_name='item',
            name='documents',
            field=models.ManyToManyField(blank=True, to='page.Document', verbose_name='Document'),
        ),
        migrations.AddField(
            model_name='item',
            name='pairs',
            field=models.ManyToManyField(blank=True, to='page.Pair', verbose_name='Pair'),
        ),
        migrations.AddField(
            model_name='item',
            name='ref_collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Collection'),
        ),
        migrations.AddField(
            model_name='item',
            name='ref_website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Website'),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Item'),
        ),
        migrations.AddField(
            model_name='document',
            name='ref_website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Website'),
        ),
        migrations.AddField(
            model_name='collection',
            name='items',
            field=models.ManyToManyField(blank=True, to='page.Item', verbose_name='Items'),
        ),
        migrations.AddField(
            model_name='collection',
            name='ref_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Page'),
        ),
        migrations.AddField(
            model_name='collection',
            name='ref_website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.Website'),
        ),
    ]
