# Generated by Django 2.2 on 2019-11-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20191112_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='value',
            field=models.TextField(verbose_name='value'),
        ),
    ]
