# Generated by Django 2.2 on 2019-05-20 13:26

from django.db import migrations, models
from website.models import Website


def create_website(apps, schema_editor):
    website = Website()
    website.name = "réunion_infra-dev_2017"
    website.url = "https://collab-famhp.yourict.be/entities/Soutien/ICTDivision/meetings/r%C3%A9union%20infra-dev%202017/default.aspx?InstanceID=20170808"
    website.prefix = "https://collab-famhp.yourict.be/entities/Soutien/ICTDivision/meetings/r%C3%A9union%20infra-dev%202017/"
    website.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='name')),
                ('running', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=1000, null=True, verbose_name='url')),
                ('prefix', models.CharField(blank=True, max_length=500, null=True, verbose_name='prefix')),
                ('pages', models.ManyToManyField(blank=True, to='page.Page', verbose_name='Pages')),
            ],
            options={
                'verbose_name': 'Website',
            },
        ),
        migrations.RunPython(create_website)
    ]
